### PR TITLE
Refactoring from LongBone into LongitudinalStructure. (This was previously just a draft pull request)

### PR DESCRIPTION
**Pull request by zennithn**
herpderp

### CODE REVIEW

**Comment by Lathreas** [comment]
Derpherp :P 

Oh, what you can do is turn this pull request into a 'draft'. That way we cannot accidentally merge it, but we will be able to organize discussions about the code you're writing until it's ready!

**Review by Lathreas — CHANGES_REQUESTED** [review]
Since you've also indicated that you'll refactor everything I suppose it's not entirely ready for a nitpick review yet, so I'll give a more general review for now that will hopefully be helpful when you continue refactoring your classes.

The most important observation is the following:
Since we want to keep the engine and the UI strictly separate, we must design the architecture such that there is no way they can intermingle. As such, I suggest that when you make new class files (*.cs), you either target Godot or you target the engine.

Godot-specific *.cs files should be put in `gui` folder and would have `using Godot;` at the top of the file. *All* classes in that file should inherit from some Godot object. That should ensure that it's a UI-related thing, such as a visual control point.

As a rule of thumb, classes (apart from internal classes perhaps) that do not inherit from Godot at all should be in the `engine` folder, and should be put in a file that doesn't have `using Godot;` at the top of the file.

Now, since you are also making things that are sort of 'between' the engine and the gui, namely a specific implementation of a Humerus bone with hard-coded values, I propose we make a third root folder besides `gui` and `engine` named `humanoid` that will be used to store a set of files that describe a humanoid character. So that folder would contain 'Humerus.cs', 'Radius.cs', 'ElbowJoint.cs' and the like. In this folder, `using Godot;` would also not be allowed to ensure no gui code is accidentally written here. Since you're not using Godot at all at the moment, I suppose you can simply remove 'using Godot.cs;' and continue working as-is. Then you can also replace `Numerics.Vector3` with simply `Vector3` because there'll be no more conflict between the types.

More general things that occur in any LongBone should be put into the `engine` folder itself, and then `Humerus.cs` would inherit from `AnatomyEngine.LongBone`.

That said, looking nice already! I think the bone-local and armature-local coordinate system should be made standard throughout the engine. If you want, I can add some classes to the engine itself that will make the bone-local, armature-local standard to use, and then we'd no longer need to worry about it in the Humerus data file.

**Comment by zennithn** [comment]
I agree that HumerusDataObjectBeforeFileIO.cs is pretty bad, and I view it as being approximately where ExampleBone.cs is in the code. Some parts should indeed go in the engine or anatomy folders - for example BoneBranchControlPoint shouldn't be in HumerusDataObjectBeforeFileIO.cs at all; I just need the code right now.

The following would be great to get into the engine or anatomy folders at some point (within ~2 weeks?), so that I could simply reference them from HumerusDataObjectBeforeFileIO.cs:
 - bone-local and armature-local coordinate system transforms like you suggest
 - BoneBranchControlPoint (or any other term that makes sense to you. Just let me know the final object name you choose. Don't bother with subclasses of BoneBranchControlPoint right now - let's just use a simple BoneBranchControlPoint class to at least get it into the API).

It's not clear yet that we need a truly separate Humerus.cs, Radius.cs, etc yet. If the API and data representation for LongBone objects is good enough, then we can get away from hard-coding values. So, let's see how far we can get with HumerusDataObjectBeforeFileIO.cs and see what can be made generalizable.

**Comment by zennithn** [comment]
@Lathreas One other thought I forgot to mention - I feel like LongBone itself could be refactored a bit to incorporate some of the data handling developed in HumerusDataObjectBeforeFileIO.cs. You understand LongBone better than I do, so I'd be afraid to take that on right now. However, after some discussion, if you find the way data is represented to be useful, I'd be happy to help with refactoring code into LongBone.

**Comment by zennithn** [comment]
Alright, here's a real first pull request! This refactors some code from LongBone into a new class LongitudinalStructure. Please also be sure to view issue https://github.com/Freedom-of-Form-Foundation/anatomy3d/issues/49

It's entirely possible I've done something that will create bugs, since I'm quite new at C#. Sorry in advance!

**Comment by zennithn** [comment]
I thought I just about had a pull request together, aaaand I just realized that in my refactoring, I completely forgot to update all of the calls to getters and setters previously present in the refactored class. Sorry about that!

**Pull request closed without merging**
